# #### PREPROCESSING CONFIGURATION ####
# General
nominal_enf: 60.0  # Hz

# LOADING
# Downsampling
downsample_per_enf: 20  # Gets multiplied by nominal_enf to obtain the downsample frequency.

# ENF ESTIMATION
# Bandpass Filter Configuration
bandpass_delta: .5  # Hz # Added and subtracted from nominal_enf to get the bandpass filter range.
bandpass_order: 1 # TODO: Explain

# FEATURE CALCULATION
# Framing
frame_len: 200  # milliseconds
frame_step: 20  # milliseconds
window_type: 'hann'  # Window type for windowing the frames.
# Frequency Estimation
n_dft: 20_000  # Number of DFT points for frequency estimation.
