# DEFAULT CONFIGURATION


# #### APPLICATION CONFIGURATION ####
create_report: False  # If True, creates report files.
classifier: 'cnn-bilstm'  # Classifier to use for classification (cnn|cnn-bilstm).

# #### CLASSIFICATION CNN ####
feature_len: 411  # Length of feature vector section for model.

# #### CLASSIFICATION CNN-BILSTM ####
bilstm_sn: 46          # number of phase points per unit frame, spatial features
bilstm_fl: 85          # number of phase points per unit frame, temporal features
bilstm_fn: 25          # number of frames, temporal features

# #### PREPROCESSING CONFIGURATION ####
# General
nominal_enf: 50.0  # Hz

# LOADING
# Downsampling
downsample_per_enf: 20  # Gets multiplied by nominal_enf to obtain the downsample frequency.

# ENF ESTIMATION
# Bandpass Filter Configuration
bandpass_delta: .5  # Hz # Added and subtracted from nominal_enf to get the bandpass filter range.
bandpass_order: 1 # TODO: Explain

# FEATURE CALCULATION
# Framing
frame_len: 200  # milliseconds
frame_step: 20  # milliseconds
window_type: 'hann'  # Window type for windowing the frames.
# Frequency Estimation
n_dft: 20_000  # Number of DFT points for frequency estimation.

# Trim
feature_trim: 40  # samples # Remove this many unusable samples from the start and end of the feature.