##CONFIG for Data preprocessing CNN 

# Nominal ENF
nominal_enf: 50.0       # Expected ENF frequency in Hz

# Windowing
window_type: 'hann'


# Downsampling
downsample_enabled: true
downsampling_frequency_per_nominal_enf: 20


# Bandpass Filter Configuration
bandpass_filter:
  is_enabled: true
  lowcut: 99.5    # Low cut frequency in Hz
  highcut: 100.5   # High cut frequency in Hz
  order: 1
  #deltaf: 0.6
  #N: 10_000


# Variational Mode Decomposition (VMD)
VMD: 
  is_enabled: false
  loop: 1              # Number of VMD iterations
  alpha: 5_000          # Balancing parameter of the data-fidelity constraint
  tau: 0               # Noise-tolerance (no strict fidelity enforcement)
  n_mode: 1            # Number of modes to be recovered
  DC: false            # True if the first mode is to be DC (0-freq)
  tol: !!float 1e-7    # Tolerance of convergence criterion


# Robust Filtering Algorithm (RFA)
RFA: 
  is_enabled: true
  f0: 50                   # estimated frequency (here ENF second harmonic)     
  I: 3                      # Number of RFA repeats
  tau: 2500             # RFA winoow size
  epsilon: !!float 1e-20    # Noise-tolerance (no strict fidelity enforcement)


# Phase Estimation Configuration
phase_estimation:
  n_dft: 20_000             # Number of points in DFT for phase estimation
  step_size: 20            # Step Size
  window_len: 200          # Window Length


# Freq Estimation Configuration
freq_estimation:
  n_dft: 20_000             # Number of points in DFT for phase estimation
  step_size: 20             # Step Size
  window_len: 200           # Window Length


feature_matrices:
  sn: 46          # number of phase points per unit frame, spatial features
  fl: 85          # number of phase points per unit frame, temporal features
  fn: 25          # number of frames, temporal features


# Plot Results
plot: true      # TODO: Switch not used yet.